package com.apps.newstudio.cash.utils;

public interface ConstantsManager {

    String EMPTY_STRING_VALUE = "";
    String TEG = "TEG FROM ";
    String LANGUAGE_KEY = "LANGUAGE_KEY";
    String LANGUAGE_ENG = "ENG";
    String LANGUAGE_RUS = "RUS";
    String LANGUAGE_UKR = "UKR";
    String LANGUAGE_CHOSEN_KEY = "LANGUAGE_CHOSEN_KEY";
    String LANGUAGE_CHOSEN = "LANGUAGE_CHOSEN";

    String LAST_UPDATE_DATE = "LAST_UPDATE_DATE";
    String SAVED_FRAGMENT_ID = "SAVED_FRAGMENT_ID";
    String ORGANIZATIONS_FILTER_PARAMETER = "ORGANIZATIONS_FILTER_PARAMETER";
    String ORGANIZATIONS_SEARCH_PARAMETER = "ORGANIZATIONS_SEARCH_PARAMETER";
    String CURRENCIES_FILTER_PARAMETER = "CURRENCIES_FILTER_PARAMETER";
    String CURRENCIES_SEARCH_PARAMETER = "CURRENCIES_SEARCH_PARAMETER";
    String ORGANIZATION_ID = "ORGANIZATION_ID";
    String ORGANIZATION_PHONE = "ORGANIZATION_PHONE";
    String ORGANIZATION_TYPE = "ORGANIZATION_TYPE";
    String ORGANIZATION_TITLE = "ORGANIZATION_TITLE";
    String ORGANIZATION_DATE = "ORGANIZATION_DATE";
    String CURRENCY_SHORT_FORM = "CURRENCY_SHORT_FORM";
    String CURRENCY_TITLE = "CURRENCY_TITLE";
    String CURRENCY_SORT_PARAMETER = "CURRENCY_SORT_PARAMETER";
    String CURRENCY_SORT_PARAMETER_TITLE = "CURRENCY_SORT_PARAMETER_TITLE";
    String CURRENCY_SORT_PARAMETER_PURCHASE = "CURRENCY_SORT_PARAMETER_PURCHASE";
    String CURRENCY_SORT_PARAMETER_SALE = "CURRENCY_SORT_PARAMETER_SALE";
    String START_ACTIVITY_MODE = "START_ACTIVITY_MODE";
    String CONVERTER_CURRENCY_SHORT_FORM_KEY = "CONVERTER_CURRENCY_SHORT_FORM_KEY";
    String CONVERTER_CURRENCY_SHORT_FORM_DEFAULT = "USD";
    String CONVERTER_ORGANIZATION_ID_KEY = "CONVERTER_ORGANIZATION_ID_KEY";
    String CONVERTER_ACTION_KEY = "CONVERTER_ACTION_KEY";
    String CONVERTER_ACTION_PURCHASE = "PURCHASE";
    String CONVERTER_ACTION_SALE = "SALE";
    String CONVERTER_DIRECTION_KEY = "CONVERTER_DIRECTION_KEY";
    String CONVERTER_DIRECTION_FROM_UAH = "CONVERTER_DIRECTION_FROM_UAH";
    String CONVERTER_DIRECTION_TO_UAH = "CONVERTER_DIRECTION_TO_UAH";
    String CONVERTER_VALUE_KEY = "CONVERTER_VALUE_KEY";
    String CONVERTER_VALUE_DEFAULT = "1";
    String CONVERTER_TEMPLATE_ID_KEY = "CONVERTER_TEMPLATE_ID_KEY";
    String CONVERTER_TEMPLATE_ID_DEFAULT = "-1";
    String CONVERTER_OPEN_FROM_KEY = "CONVERTER_OPEN_FROM_KEY";
    String CONVERTER_OPEN_FROM_TEMPLATES = "CONVERTER_OPEN_FROM_TEMPLATES";
    String CONVERTER_OPEN_FROM_CURRENCY = "CONVERTER_OPEN_FROM_CURRENCY";
    String CONVERTER_OPEN_FROM_ORGANIZATION = "CONVERTER_OPEN_FROM_ORGANIZATION";
    String NOTIFICATION_CHANNEL_ID = "NOTIFICATION_CHANNEL_ID";

    int ORGANIZATION_FRAGMENT_REQUEST_CODE = 1;
    int ORGANIZATION_ACTIVITY_REQUEST_CODE = 2;
    int CURRENCY_ACTIVITY_RESULT_CODE_CHANGE_DATA = 3;

    int CURRENCY_FRAGMENT_REQUEST_CODE = 11;
    int CURRENCY_ACTIVITY_REQUEST_CODE = 21;
    int ORGANIZATION_ACTIVITY_RESULT_CODE_CHANGE_DATA = 31;

    int TEMPLATES_FRAGMENT_REQUEST_CODE = 41;
    int CONVERTER_ACTIVITY_RESULT_CODE_CHANGED = 42;

}
