package com.apps.newstudio.cash.utils;

public interface ConstantsManager {

    String EMPTY_STRING_VALUE = "";
    String TAG = "TEG FROM ";
    String LANGUAGE_KEY = "LANGUAGE_KEY";
    String LANGUAGE_ENG = "ENG";
    String LANGUAGE_RUS = "RUS";
    String LANGUAGE_UKR = "UKR";
    String LAST_UPDATE_DATE = "LAST_UPDATE_DATE";
    String SAVED_FRAGMENT_ID = "SAVED_FRAGMENT_ID";
    String ORGANIZATIONS_FILTER_PARAMETER = "ORGANIZATIONS_FILTER_PARAMETER";
    String ORGANIZATIONS_SEARCH_PARAMETER = "ORGANIZATIONS_SEARCH_PARAMETER";
    String CURRENCIES_FILTER_PARAMETER = "CURRENCIES_FILTER_PARAMETER";
    String CURRENCIES_SEARCH_PARAMETER = "CURRENCIES_SEARCH_PARAMETER";
    String ORGANIZATION_ID = "ORGANIZATION_ID";
    String ORGANIZATION_PHONE = "ORGANIZATION_PHONE";
    String ORGANIZATION_TYPE = "ORGANIZATION_TYPE";
    String ORGANIZATION_TITLE = "ORGANIZATION_TITLE";
    String ORGANIZATION_DATE = "ORGANIZATION_DATE";
    String CURRENCY_SHORT_FORM = "CURRENCY_SHORT_FORM";
    String CURRENCY_TITLE = "CURRENCY_TITLE";
    String CURRENCY_SORT_PARAMETER = "CURRENCY_SORT_PARAMETER";
    String CURRENCY_SORT_PARAMETER_TITLE = "CURRENCY_SORT_PARAMETER_TITLE";
    String CURRENCY_SORT_PARAMETER_PURCHASE = "CURRENCY_SORT_PARAMETER_PURCHASE";
    String CURRENCY_SORT_PARAMETER_SALE = "CURRENCY_SORT_PARAMETER_SALE";



    int ORGANIZATION_FRAGMENT_REQUEST_CODE = 1;
    int ORGANIZATION_ACTIVITY_REQUEST_CODE = 2;

    int CURRENCY_FRAGMENT_REQUEST_CODE = 11;
    int CURRENCY_ACTIVITY_REQUEST_CODE = 21;

}
